on:  
  workflow_dispatch:
  repository_dispatch:
    types:
        update
  push: 
    branches: [main]
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        token: ${{ secrets.REPO_TOKEN }}
    - name: update nearorg_marketing
      run: |
        git submodule init
        git submodule update --remote --merge
        git config --local user.email "devconsole-team@pagoda.co"
        git config --local user.name "github-actions-bot"
        git commit -m "update submodule in response to marketing content update" -a
        git push
