on:  
  push: 
    branches: [main]
  workflow_dispatch:
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: do-this
      run: |
        git submodule init
        git submodule update --remote --merge
        git config --local user.email "devconsole-team@pagoda.co"
        git config --local user.name "github-actions[bot]"
        git commit -m "update submodule in response to marketing content update" -a
        git push
